spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hello
    username: postgres
    password: 91115101
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: /
    connection-timeout: 15000
    requested-heartbeat: 30

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.amqp: DEBUG
